### ISSUE TITLE
最新提交的版本使用报错，Mac环境

### ISSUE THREAD

**Issue by OrdinaryFish** [ice1000/A8Translate#9]
![image](https://user-images.githubusercontent.com/6408198/48604929-48d46980-e9b6-11e8-8783-a680cd51f010.png)

**Comment by thecoding** [comment]
### 
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:888)
	at com.google.gson.Gson.fromJson(Gson.java:853)
	at com.google.gson.Gson.fromJson(Gson.java:802)
	at org.a8sport.translate.net.HttpUtils.requestNetData(HttpUtils.java:37)
	at org.a8sport.translate.main.TranslateAction.performTranslation(TranslateAction.java:62)
	at org.a8sport.translate.main.TranslateAction.actionPerformed(TranslateAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:561)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:610)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:609)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:464)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 22 more


JSON解析报错了。

**Comment by ice1000** [comment]
woc

**Comment by ice1000** [comment]
我怎么记得我修过一个一模一样的问题

**Comment by thecoding** [comment]
我的版本是1.4的

**Comment by thecoding** [comment]
android studio 上面有两个版本，没注意看时间

**Comment by ddbXJ** [comment]
> ![image](https://user-images.githubusercontent.com/16398479/48682865-60f3e680-eb78-11e8-99b0-45528c295808.png)
> 
> 这都1.7了啊..更新试试?

我刚刚安装了1.7 报同样的错
![2018-11-28 4 20 49](https://user-images.githubusercontent.com/13849193/49138247-ad35e800-f329-11e8-8a7e-f77cd4e80fa4.png)

**Comment by ice1000** [comment]
好的

**Comment by ice1000** [comment]
这应该是本身查询就出错了，但是错误处理没写好

**Comment by ikomom** [comment]
> 这应该是本身查询就出错了，但是错误处理没写好

我也报同样的错，window环境

**Comment by ice1000** [comment]
我修改了错误处理，改成输出JSON了，如果还出现的话就可以看到具体的json了。
然后再解决具体的问题吧，现在主要是不知道咋整。
